<?php
/**
 * @var Amasty\Dpanko\Block\Index $block
 */

?>

<div style="<?= $block->getClasses() ?>">
    <form name="form" method="POST" action="#">

        <p><input type="text" name="sku" placeholder="Text"></p>
        <p><input type="number" name="qty" placeholder="Number"></p>
        <p><?= $block->getChildHtml('Amasty_Dpanko_additional') ?></p>
        <p><input type="submit" value="Отправить""></p>
</div>

</form>