<?php
/**
 * @var Amasty\Dpanko\Block\Index $block
 */


?>

<div>

   <form name="form" method="POST" action="#">

       <p><input type="text" name="sku" placeholder="Sku" data-validate='{"required":true}'></p>

        <?php if ($block->enabledQTY()): ?>
           <p><input type="number" name="qty" value="--><?= $block->fieldQTY() ?>"
                     data-validate='{"required":true, "min":1}'></p>
       <?php endif; ?>
<?= $block->getChildHtml('Amasty_Dpanko_additional') ?>
        <p><input type="submit" value="Отправить"
                  formaction="form.php" formmethod="post"></p>


